// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grywannxkhjcivuzihnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeXdhbm54a2hqY2l2dXppaG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTgwMzgsImV4cCI6MjA1NzY5NDAzOH0.kT4gThHwYbfNkN8qu4Isqq6C6vJ4Rtn9vszEFMJyEMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);