// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjncrdzdeghacbejapka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbmNyZHpkZWdoYWNiZWphcGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDExMTksImV4cCI6MjA1Nzc3NzExOX0.tw6HkHPJ9znCPA8xK9v_9ASjPr-jaFIcrSHeBMFs1Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);